// Fina/fina/fina.jsx
import React, { useState } from "react";
import "./fina.css";

function FinaApp() {
  const [transactions, setTransactions] = useState([]);
  const [description, setDescription] = useState("");
  const [amount, setAmount] = useState("");

  // Calcula valores
  const income = transactions
    .filter((t) => t.amount > 0)
    .reduce((acc, t) => acc + t.amount, 0);

  const expenses = transactions
    .filter((t) => t.amount < 0)
    .reduce((acc, t) => acc + t.amount, 0);

  const balance = income + expenses;

  // Adicionar transação
  const handleAdd = (e) => {
    e.preventDefault();
    if (!description || isNaN(amount)) return alert("Preencha os campos corretamente!");

    const newTransaction = {
      id: Date.now(),
      description,
      amount: parseFloat(amount),
    };

    setTransactions([newTransaction, ...transactions]);
    setDescription("");
    setAmount("");
  };

  // Limpar histórico
  const clearHistory = () => {
    if (window.confirm("Tem certeza que deseja limpar o histórico?")) {
      setTransactions([]);
    }
  };

  // Navegação simples
  const handleLogout = () => (window.location.href = "fina-login.html");
  const goToReports = () => (window.location.href = "MeuRelatorio.html");
  const goToContacts = () => (window.location.href = "contatos.html");

  return (
    <div>
      <header>
        <div className="header-content">
          <h1>💰 Fina</h1>

          <div className="header-buttons">
            <button onClick={goToContacts}>Contatos</button>
            <button onClick={goToReports}>Relatórios</button>
          </div>

          <button id="logout-btn" className="logout-btn" onClick={handleLogout}>
            Sair
          </button>
        </div>
        <p>Seu controle financeiro simples e rápido</p>
      </header>

      <main className="container">
        {/* Saldo */}
        <section className="balance-section">
          <h2>Saldo atual</h2>
          <div id="balance">
            {balance.toLocaleString("pt-BR", {
              style: "currency",
              currency: "BRL",
            })}
          </div>
        </section>

        {/* Formulário */}
        <section className="form-section">
          <h2>Adicionar Transação</h2>
          <form onSubmit={handleAdd}>
            <input
              type="text"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Descrição"
              required
            />
            <input
              type="text"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              placeholder="Valor (use negativo para saída)"
              required
            />
            <button type="submit">Adicionar</button>
          </form>
        </section>

        {/* Resumo */}
        <section className="summary-section">
          <div>
            <h3>Entradas</h3>
            <div>
              {income.toLocaleString("pt-BR", {
                style: "currency",
                currency: "BRL",
              })}
            </div>
          </div>
          <div>
            <h3>Saídas</h3>
            <div>
              {Math.abs(expenses).toLocaleString("pt-BR", {
                style: "currency",
                currency: "BRL",
              })}
            </div>
          </div>
        </section>

        {/* Histórico */}
        <section className="list-section">
          <h2>Histórico</h2>
          <ul id="transactions">
            {transactions.length === 0 ? (
              <li>Nenhuma transação registrada</li>
            ) : (
              transactions.map((t) => (
                <li key={t.id} className={t.amount < 0 ? "negative" : "positive"}>
                  {t.description} —{" "}
                  {t.amount.toLocaleString("pt-BR", {
                    style: "currency",
                    currency: "BRL",
                  })}
                </li>
              ))
            )}
          </ul>
          <button onClick={clearHistory}>Limpar histórico</button>
        </section>
      </main>

      <footer>© 2025 Fina - Luiz Felipe</footer>
    </div>
  );
}

export default FinaApp;

// Fina/fina/fina.vue
<template>
  <div>
    <header>
      <div class="header-content">
        <h1>💰 Fina</h1>

        <div class="header-buttons">
          <button @click="goToContacts">Contatos</button>
          <button @click="goToReports">Relatórios</button>
        </div>

        <div class="header-right">
          <button class="logout-btn" @click="logout">Sair</button>
          <button class="delete-btn" @click="deleteAccount">Excluir Conta</button>
        </div>
      </div>

      <p>Seu controle financeiro simples e rápido</p>
    </header>

    <main class="container">
      <!-- Saldo -->
      <section class="balance-section">
        <h2>Saldo atual</h2>
        <div>{{ formattedBalance }}</div>
      </section>

      <!-- Formulário -->
      <section class="form-section">
        <h2>Adicionar Transação</h2>
        <form @submit.prevent="addTransaction">
          <input v-model="description" type="text" placeholder="Descrição" required />
          <input v-model="amount" type="text" placeholder="Valor (use negativo para saída)" required />
          <button type="submit">Adicionar</button>
        </form>
      </section>

      <!-- Resumo -->
      <section class="summary-section">
        <div>
          <h3>Entradas</h3>
          <div>{{ formattedIncome }}</div>
        </div>
        <div>
          <h3>Saídas</h3>
          <div>{{ formattedExpenses }}</div>
        </div>
      </section>

      <section class="list-section">
        <h2>Histórico</h2>
        <ul>
          <li v-for="(t, index) in transactions" :key="index">
            {{ t.description }} — {{ formatCurrency(t.amount) }}
          </li>
        </ul>
        <button @click="clearHistory">Limpar histórico</button>
      </section>
    </main>

    <footer>© 2025 Fina - Luiz Felipe</footer>
  </div>
</template>

<script>
export default {
  name: "FinaApp",
  data() {
    return {
      description: "",
      amount: "",
      transactions: []
    };
  },
  computed: {
    balance() {
      return this.transactions.reduce((acc, t) => acc + Number(t.amount), 0);
    },
    income() {
      return this.transactions
        .filter(t => Number(t.amount) > 0)
        .reduce((acc, t) => acc + Number(t.amount), 0);
    },
    expenses() {
      return this.transactions
        .filter(t => Number(t.amount) < 0)
        .reduce((acc, t) => acc + Number(t.amount), 0);
    },
    formattedBalance() {
      return this.formatCurrency(this.balance);
    },
    formattedIncome() {
      return this.formatCurrency(this.income);
    },
    formattedExpenses() {
      return this.formatCurrency(this.expenses);
    }
  },
  methods: {
    formatCurrency(value) {
      return Number(value).toLocaleString("pt-BR", {
        style: "currency",
        currency: "BRL"
      });
    },
    addTransaction() {
      const amountNumber = Number(this.amount.replace(",", "."));
      if (isNaN(amountNumber)) return alert("Valor inválido!");

      this.transactions.push({
        description: this.description,
        amount: amountNumber
      });

      this.description = "";
      this.amount = "";
      this.save();
    },
    clearHistory() {
      if (confirm("Tem certeza que deseja limpar tudo?")) {
        this.transactions = [];
        this.save();
      }
    },
    save() {
      localStorage.setItem("transactions", JSON.stringify(this.transactions));
    },
    load() {
      const data = JSON.parse(localStorage.getItem("transactions"));
      if (Array.isArray(data)) this.transactions = data;
    },
    goToContacts() {
      window.location.href = "contatos.html";
    },
    goToReports() {
      window.location.href = "MeuRelatorio.html";
    },
    logout() {
      window.location.href = "fina-login.html";
    },
    deleteAccount() {
      if (confirm("Deseja realmente excluir sua conta?")) {
        localStorage.clear();
        alert("Conta excluída!");
        window.location.href = "fina-login.html";
      }
    }
  },
  mounted() {
    this.load();
  }
};
</script>

<style scoped>
/* estilos podem ser importados do seu fina.css */
</style>
