// Fina/fina/MeuRelatorio.vue
<template>
  <div>
    <header>
      <div class="header-wrapper">
        <div>
          <h1>📊 Relatórios — Fina</h1>
          <div class="subtitle">Visão de gastos por categoria e por mês</div>
        </div>
        <div>
          <button id="back-btn" class="back-btn" @click="goBack">← Voltar</button>
        </div>
      </div>
    </header>

    <main class="container">
      <section class="card">
        <div class="controls">
          <label for="from">De:</label>
          <input type="date" v-model="from" />

          <label for="to">Até:</label>
          <input type="date" v-model="to" />

          <select v-model="groupBy">
            <option value="all">Todos os dados</option>
            <option value="month">Agrupar por mês</option>
          </select>

          <button @click="refreshCharts">Atualizar</button>
          <button @click="downloadPNG">Exportar PNG</button>
        </div>
        <div class="tip">Selecione um intervalo de datas para filtrar os dados dos gráficos. Se nenhum dado existir no localStorage, a página usará dados de exemplo.</div>
      </section>

      <div class="row">
        <div class="card">
          <h2>Distribuição por categoria (Pizza)</h2>
          <canvas ref="pieCanvas"></canvas>
        </div>

        <div class="card">
          <h2>Gastos por mês (Barras)</h2>
          <canvas ref="barCanvas"></canvas>
        </div>
      </div>

      <div class="card">
        <h2>Lista resumida</h2>
        <div id="summary-list">
          <div v-for="(item, index) in summary" :key="index" class="summary-item">
            <strong>{{ item.name }}:</strong> {{ formatCurrency(item.total) }}
          </div>
        </div>
      </div>
    </main>

    <footer>© 2025 Fina - Luiz Felipe</footer>
  </div>
</template>

<script>
import Chart from "chart.js/auto";

export default {
  name: "RelatoriosFina",
  data() {
    return {
      from: "",
      to: "",
      groupBy: "all",
      transactions: [],
      pieChart: null,
      barChart: null,
      summary: []
    };
  },
  methods: {
    goBack() {
      window.location.href = "fina.html";
    },
    formatCurrency(v) {
      return Number(v).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
    },
    loadData() {
      const stored = JSON.parse(localStorage.getItem("transactions"));
      if (Array.isArray(stored)) this.transactions = stored;
      else {
        this.transactions = [
          { description: "Mercado", amount: -120, category: "Alimentação", date: "2025-02-01" },
          { description: "Salário", amount: 2500, category: "Trabalho", date: "2025-02-05" },
          { description: "Energia", amount: -180, category: "Casa", date: "2025-02-10" }
        ];
      }
    },
    filterData() {
      return this.transactions.filter(t => {
        if (this.from && t.date < this.from) return false;
        if (this.to && t.date > this.to) return false;
        return true;
      });
    },
    refreshCharts() {
      const data = this.filterData();

      // --- RESUMO POR CATEGORIA ---
      const categories = {};
      data.forEach(t => {
        categories[t.category] = (categories[t.category] || 0) + Number(t.amount);
      });
      this.summary = Object.entries(categories).map(([name, total]) => ({ name, total }));

      // --- GRÁFICO DE PIZZA ---
      if (this.pieChart) this.pieChart.destroy();
      this.pieChart = new Chart(this.$refs.pieCanvas, {
        type: "pie",
        data: {
          labels: Object.keys(categories),
          datasets: [{ data: Object.values(categories) }]
        }
      });

      // --- GRÁFICO DE BARRAS POR MÊS ---
      const monthly = {};
      data.forEach(t => {
        const month = t.date.slice(0, 7);
        monthly[month] = (monthly[month] || 0) + Number(t.amount);
      });

      if (this.barChart) this.barChart.destroy();
      this.barChart = new Chart(this.$refs.barCanvas, {
        type: "bar",
        data: {
          labels: Object.keys(monthly),
          datasets: [{ data: Object.values(monthly) }]
        }
      });
    },
    downloadPNG() {
      const pie = this.$refs.pieCanvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = pie;
      link.download = "relatorio_fina.png";
      link.click();
    }
  },
  mounted() {
    this.loadData();
    this.refreshCharts();
  }
};
</script>

<style scoped>
.header-wrapper {
  max-width: 1100px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.subtitle {
  font-size: 0.9rem;
  opacity: 0.9;
}
.back-btn {
  background: blue;
  color: white;
  border: none;
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  padding: 6px 12px;
}
.row {
  display: flex;
  gap: 20px;
  margin-top: 20px;
}
.card {
  padding: 18px;
  background: #ffffff20;
  border-radius: 12px;
  backdrop-filter: blur(6px);
}
.controls {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
  margin-bottom: 10px;
}
.tip {
  opacity: 0.9;
  margin-top: 6px;
}
.summary-item {
  padding: 4px 0;
}
</style>

// Fina/fina/MeuRelatorio.jsx
import React, { useEffect } from "react";
import "./fina.css";

const Relatorio = () => {
  useEffect(() => {
    const backBtn = document.getElementById("back-btn");
    if (backBtn) {
      backBtn.addEventListener("click", () => {
        window.location.href = "fina.html";
      });
    }

    // Carrega o script externo (MeuRelatorio.js)
    const script = document.createElement("script");
    script.src = "MeuRelatorio.js";
    script.async = true;
    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return (
    <div style={{ background: "#f5f7fb", color: "#222", fontFamily: "'Poppins', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial" }}>
      <header
        style={{
          padding: "18px 20px",
          background: "linear-gradient(90deg,#6d6df1 0%, #4aa3ff 100%)",
          color: "white",
        }}
      >
        <div
          style={{
            maxWidth: "1100px",
            margin: "0 auto",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <div>
            <h1 style={{ margin: 0 }}>📊 Relatórios — Fina</h1>
            <div style={{ fontSize: "0.9rem", opacity: 0.95 }}>
              Visão de gastos por categoria e por mês
            </div>
          </div>
          <div>
            <button
              id="back-btn"
              style={{
                background: "blue",
                border: "none",
                color: "white",
                fontWeight: 600,
                cursor: "pointer",
                fontSize: "1rem",
                borderRadius: "6px",
                padding: "8px 12px",
              }}
            >
              ← Voltar
            </button>
          </div>
        </div>
      </header>

      <main className="container" style={{ maxWidth: "1100px", margin: "20px auto", padding: "16px" }}>
        <section className="card" style={cardStyle}>
          <div className="controls" style={controlsStyle}>
            <label htmlFor="from">De:</label>
            <input type="date" id="from" />
            <label htmlFor="to">Até:</label>
            <input type="date" id="to" />
            <select id="group-by">
              <option value="all">Todos os dados</option>
              <option value="month">Agrupar por mês</option>
            </select>
            <button id="refresh">Atualizar</button>
            <button id="download-png">Exportar PNG</button>
          </div>
          <div style={{ marginTop: "6px" }}>
            Selecione um intervalo de datas para filtrar os dados dos gráficos. Se nenhum dado existir no localStorage, a página usará dados de exemplo.
          </div>
        </section>

        <div
          className="row"
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: "18px",
            marginBottom: "18px",
          }}
        >
          <div className="card" style={cardStyle}>
            <h2>Distribuição por categoria (Pizza)</h2>
            <canvas id="pieChart" style={canvasStyle}></canvas>
          </div>

          <div className="card" style={cardStyle}>
            <h2>Gastos por mês (Barras)</h2>
            <canvas id="barChart" style={canvasStyle}></canvas>
          </div>
        </div>

        <div className="card" style={cardStyle}>
          <h2>Lista resumida</h2>
          <div id="summary-list"></div>
        </div>
      </main>

      <footer style={{ textAlign: "center", color: "#666", padding: "18px 0" }}>
        © 2025 Fina - Luiz Felipe
      </footer>
    </div>
  );
};

// estilos reutilizáveis
const cardStyle = {
  background: "white",
  borderRadius: "12px",
  padding: "14px",
  boxShadow: "0 6px 18px rgba(16,24,40,0.06)",
};

const controlsStyle = {
  display: "flex",
  gap: "8px",
  alignItems: "center",
  marginBottom: "10px",
};

const canvasStyle = {
  width: "100%",
  height: "320px",
};

export default Relatorio;
